---
title: "BTC DPT Visium STD Cohort - EPI Subtyping with CODA"
author: "Meredith Wetzel"
date: "2025-08-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
rm(list = ls())
library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(RColorBrewer)
library(EnhancedVolcano)
library(fgsea)
library(DESeq2)
library(DT)
library(ggbiplot)
library(reshape2)
library(ggpubr)
library(CoGAPS)
library(SeuratDisk)
options(future.globals.maxSize = 8000 * 1024^2)
set.seed(1234)
```

```{r include=FALSE}
obj.dir <- "../objects/"
```

```{r}
coda.cols <- c('pink2','orange','grey','red','turquoise3','darkgreen','blue','yellow','purple','brown')
names(coda.cols) <- c('stroma','vasculature','NA','responding','non-responding','normal duct','mixed','islets','nerve','fat')

rctd.cols <- c('pink2','orange','darkgreen','turquoise3','red','blue','yellow','purple','brown','magenta','cornflowerblue')
names(rctd.cols) <- c('FIBROBLASTS','PERICYTES','CYCLING DUCTAL','DUCTAL','ENDOCRINE','ACINAR','PLASMA','TNK','B CELLS','CYCLING. MYELOID','MYELOID')
```

```{r}
load(file = paste0(obj.dir,"final_objects/visiumSTD_merged_CODAupdated.rda"))
```

```{r}
info <- sobj@meta.data
```

```{r fig.height=10, fig.width=10}
SpatialDimPlot(sobj, group.by = "CODA", ncol = 2, pt.size.factor = 8, cols = coda.cols)
```

```{r warning=FALSE}
# subset to just the EPI
Idents(sobj) <- 'CODA'
sobj.pdac <- subset(sobj, idents = c("non-responding","responding"))
```

```{r fig.height=10, fig.width=10}
SpatialDimPlot(sobj.pdac, group.by = "cell_type_rctd", ncol = 2, pt.size.factor = 8, cols = rctd.cols)
SpatialDimPlot(sobj.pdac, group.by = "CODA", ncol = 2, pt.size.factor = 8, cols = coda.cols)
```

```{r}
# gene lists
pancaf_genes <- list(c('LUM','DCN','COL1A1','VIM','CD39','FSP1','FAP','ACTA2','PDPN'))
basal_genes <- list(c('VGLL','UCA1','S100A2','LY6D','SPRR3','SPRR1B','LEMD1','KRT15',
                      'CTSL2','DHRS9','AREG','CST6','SERPINB3','KRT6C','KRT6A','SERPINB4',
                      'FAM83A','SCEL','FGFBP1','KRT7','KRT17','GPR87','TNS4','SLC2A1',
                      'ANXA8L2'))
classical_genes <- list(c('BTNL8','FAM3D','ATAD4','AGR3','CTSE','LOC400573','LYZ','TFF2',
                          'TFF1','ANXA10','LGALS4','PLA2G10','CEACAM6','VSIG2','TSPAN8',
                          'ST6GALNAC1','AGR2','TFF3','CYP3A7','MYO1A','CLRN3','KRT20',
                          'CDH17','SPINK4','REG4'))
```

```{r}
sobj.pdac <- AddModuleScore(sobj.pdac, features = pancaf_genes, name = "panCAF")
sobj.pdac <- AddModuleScore(sobj.pdac, features = basal_genes, name = "basal")
sobj.pdac <- AddModuleScore(sobj.pdac, features = classical_genes, name = "classical")
```

```{r fig.height=10, fig.width=10}
SpatialFeaturePlot(sobj.pdac, features = "panCAF1", ncol = 2, pt.size.factor = 8)
SpatialFeaturePlot(sobj.pdac, features = "basal1", ncol = 2, pt.size.factor = 8)
SpatialFeaturePlot(sobj.pdac, features = "classical1", ncol = 2, pt.size.factor = 8)
```

<!-- ```{r} -->
<!-- sobj.pdac_df <- data.frame(cbind(sobj.pdac$classical1, sobj.pdac$basal1, "Intermediate")) -->
<!-- colnames(sobj.pdac_df) <- c("Classical", "Basal", "Type") -->
<!-- id1 <- intersect(which(sobj.pdac$basal1 < sobj.pdac$classical1 - 0.2), which(as.numeric(sobj.pdac$classical1) > 0.2)) -->
<!-- id2 <- intersect(which(sobj.pdac$basal1 > sobj.pdac$classical1 + 0.2), which(as.numeric(sobj.pdac$basal1) > 0.2)) -->
<!-- id3 <- intersect(which(sobj.pdac$basal1 < sobj.pdac$classical1 + 0.2), which(sobj.pdac$basal1 > sobj.pdac$classical1 - 0.2)) -->
<!-- sobj.pdac_df$Type[id1] <- "Classical" -->
<!-- sobj.pdac_df$Type[id2] <- "Basal" -->
<!-- sobj.pdac_df$Type[id3] <- "Intermediate" -->
<!-- sobj.pdac_df$Classical <- as.numeric(sobj.pdac_df$Classical) -->
<!-- sobj.pdac_df$Basal <- as.numeric(sobj.pdac_df$Basal) -->
<!-- sobj.pdac_df$Type <- factor(sobj.pdac_df$Type, levels = c("Classical", "Intermediate", "Basal")) -->
<!-- ``` -->

```{r}
sobj.pdac_df <- data.frame(Classical = as.numeric(sobj.pdac$classical1),
                      Basal = as.numeric(sobj.pdac$basal1),
                      panCAF = as.numeric(sobj.pdac$panCAF1),
                      Type = "Mix")
threshold <- 0.2
sobj.pdac_df$Type <- apply(sobj.pdac_df[, c("Classical", "Basal", "panCAF")], 1, function(x) {
  diffs <- x - max(x)
  if (sum(diffs == 0) == 1 && max(x) > threshold &&
      all(abs(diffs[diffs != 0]) > threshold)) {
    return(names(x)[which.max(x)])
  } else {
    return("Mix")
  }
})
sobj.pdac_df$Type <- factor(sobj.pdac_df$Type, levels = c("Classical", "Basal", "panCAF", "Mix"))
```

```{r}
# add annotation to seurat object
sobj.pdac <- AddMetaData(sobj.pdac, sobj.pdac_df, col.name = "Type")
```

```{r}
table(sobj.pdac_df$Type)
```

```{r}
#plotting color scheme
type.color <- c("green4","blue2","mediumpurple1")
names(type.color) <- c("Basal","Classical","Intermediate")
```

```{r fig.height=15, fig.width=10}
SpatialDimPlot(sobj.pdac, group.by = "Type", ncol = 2, pt.size.factor = 8, image.alpha = 0.5, cols = type.color)
```

```{r fig.height=4, fig.width=4}
props <- stack_cell_porportions(sobj.pdac, group.by.x = "sample", group.by.stack = "Type")
plot_stack(props, group.by.x = "sample", group.by.stack = "Type") + scale_fill_manual(values = type.color)
```

```{r fig.height=4, fig.width=4}
props <- stack_cell_porportions(sobj.pdac, group.by.x = "sample", group.by.stack = "cell_type_rctd")
plot_stack(props, group.by.x = "sample", group.by.stack = "cell_type_rctd") + scale_fill_manual(values = rctd.cols)
```

```{r}
table(sobj.pdac$CODA,sobj.pdac$cell_type_rctd)
table(sobj.pdac$Type,sobj.pdac$cell_type_rctd)

table(sobj.pdac$CODA,sobj.pdac$Type)
table(sobj.pdac$Type,sobj.pdac$CODA)
```

```{r}
# save objects
save(sobj.pdac, file = paste0(obj.dir,"final_objects/visiumSTD_merged_EPI_VBsubtype_CODAupdated.rda"))
```

```{r}
sessionInfo()
```
