---
title: "Epithelial Subtyping (Vince's Code)"
author: "Meredith Wetzel"
date: "2025-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
rm(list = ls())
library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(RColorBrewer)
library(EnhancedVolcano)
library(fgsea)
library(DESeq2)
library(DT)
library(ggbiplot) 
library(reshape2)
library(ggpubr)
library(CoGAPS)
library(SeuratDisk)
source(file = "../../../stacked_props_function.R")
options(future.globals.maxSize = 8000 * 1024^2)
set.seed(1234)
```

```{r include=FALSE}
obj.dir <- "/projects/btcpilot_visiumhd/objects/"
#obj.dir <- "/projects/btcpilot_visiumhd/objects/codeCheck/"
```

```{r}
# load(file = paste0(obj.dir,"merged_016um_seurObj_updated.rda")) # need to go through all the object names
load(file = paste0(obj.dir,"final_codeCheck/merged_annotated_016um_seurObj.rda")) 
info <- sobj@meta.data
```

# EPI Gene Signatures
```{r}
basal_genes <- c('VGLL','UCA1','S100A2','LY6D','SPRR3','SPRR1B','LEMD1','KRT15',
                      'CTSL2','DHRS9','AREG','CST6','SERPINB3','KRT6C','KRT6A','SERPINB4',
                      'FAM83A','SCEL','FGFBP1','KRT7','KRT17','GPR87','TNS4','SLC2A1',
                      'ANXA8L2')
classical_genes <- c('BTNL8','FAM3D','ATAD4','AGR3','CTSE','LOC400573','LYZ','TFF2',
                          'TFF1','ANXA10','LGALS4','PLA2G10','CEACAM6','VSIG2','TSPAN8',
                          'ST6GALNAC1','AGR2','TFF3','CYP3A7','MYO1A','CLRN3','KRT20',
                          'CDH17','SPINK4','REG4')
```

# Subset to just fibroblasts (based on RCTD)
```{r}
# Idents(sobj) <- "cell_type_rctd"
Idents(sobj) <- "cell_type"
sobj.epi <- subset(sobj, idents = "PDAC") # for updated RCTD
# sobj.epi <- subset(sobj, idents = c("CYCLING DUCTAL","DUCTAL")) # for original

sobj.epi <- JoinLayers(sobj.epi)
```

```{r}
# run module scores for EPI subtypes
sobj.epi <- AddModuleScore(sobj.epi, features = list(classical_genes),name = "Classical")
sobj.epi <- AddModuleScore(sobj.epi, features = list(basal_genes),name = "Basal")
```

```{r}
# Min-max normalization function for module scores
min_max_norm <- function(x) {
  (x - min(x, na.rm = TRUE)) / (max(x, na.rm = TRUE) - min(x, na.rm = TRUE))
}
```

```{r}
# run normalization
sobj.epi$Classical_norm <- min_max_norm(sobj.epi$Classical1)
sobj.epi$Basal_norm <- min_max_norm(sobj.epi$Basal1)
```

# Use our module scores but Vince's classification method
```{r}
sobj.epi_df <- data.frame(cbind(sobj.epi$Classical_norm, sobj.epi$Basal_norm, "Intermediate"))
colnames(sobj.epi_df) <- c("Classical", "Basal", "Type")
```

```{r}
id1 <- intersect(which(sobj.epi$Basal_norm < sobj.epi$Classical_norm - 0.2), which(as.numeric(sobj.epi$Classical_norm) > 0.2))
id2 <- intersect(which(sobj.epi$Basal_norm > sobj.epi$Classical_norm + 0.2), which(as.numeric(sobj.epi$Basal_norm) > 0.2))
id3 <- intersect(which(sobj.epi$Basal_norm < sobj.epi$Classical_norm + 0.2), which(sobj.epi$Basal_norm > sobj.epi$Classical_norm - 0.2))
sobj.epi_df$Type[id1] <- "Classical"
sobj.epi_df$Type[id2] <- "Basal"
sobj.epi_df$Type[id3] <- "Intermediate"
```

```{r}
sobj.epi_df$Classical <- as.numeric(sobj.epi_df$Classical)
sobj.epi_df$Basal <- as.numeric(sobj.epi_df$Basal)
sobj.epi_df$Type <- factor(sobj.epi_df$Type, levels = c("Classical", "Intermediate", "Basal"))
```

```{r}
# add annotation to seurat object
sobj.epi <- AddMetaData(sobj.epi, sobj.epi_df, col.name = "Type")
```

```{r}
table(sobj.epi_df$Type)
```

```{r fig.height=10, fig.width=15}
sub.cols <- c("green4","blue2","mediumpurple1")
names(sub.cols) <- c("Basal","Classical","Intermediate")
SpatialDimPlot(sobj.epi, ncol = 3, pt.size.factor = 8, image.alpha = 0.5, group.by = "Type", cols = sub.cols)
```

```{r fig.height=8, fig.width=8, warning=FALSE}
props <- stack_cell_porportions(sobj.epi, group.by.x = "sample",group.by.stack = "Type")
plot_stack(props, group.by.x = "sample",group.by.stack = "Type") + scale_fill_manual(values = sub.cols)
```

```{r}
# save object
#save(sobj.epi, file = paste0(obj.dir,"EPIsubtypes_016um_seurObj.rda"))
save(sobj.epi, file = paste0(obj.dir,"final_codeCheck/PDACsubtypes_016um_seurObj.rda"))
```

```{r}
sessionInfo()
```
